# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./feed.h
SOURCES += ./feed.cpp \
    ./main.cpp
FORMS += ./feed.ui
RESOURCES += feed.qrc
